### ISSUE TITLE
Build fails on Vercel free plan because edge function is 1.05 MB

### ISSUE THREAD

**Issue by maddyonline** [steven-tey/weathergpt#1]
![Screenshot 2023-04-14 at 12 45 20 AM](https://user-images.githubusercontent.com/6402895/231978691-2c958c8d-3d1f-4235-8a2a-d3f8a95e92bf.png)

Wonder if it can be optimized to fit in 1 MB?

**Comment by steven-tey** [comment]
ooof good catch, can repro, looking into this now! thanks for the heads-up!

**Comment by steven-tey** [comment]
ok this commit should fix this: https://github.com/steven-tey/weathergpt/commit/45897f81dc5520a12bb16f3470e8aa3d83804ee1

I was trying to fit a 1MB SVG into the edge function <picture data-single-emoji=":lol:" title=":lol:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lol/5986e156eca2154f.png" alt=":lol:" align="absmiddle"></picture> 

![CleanShot 2023-04-14 at 13 16 12](https://user-images.githubusercontent.com/28986134/232124993-53fb05ea-b328-4253-9457-1564cfa437e8.png)

**Comment by steven-tey** [comment]
Had to remove the Inter font, but confirmed it's fixed now! :)
