### ISSUE TITLE
Unable to install plugin when self deploying on Vercel

### ISSUE THREAD

**Issue by maddyonline** [steven-tey/weathergpt#2]
I followed the instructions to deploy to Vercel and created this repo: https://github.com/maddyonline/weathergpt. The app itself works fine: https://weathergpt-kqtv.vercel.app/. 

I even updated `public/.well-known/ai-plugin.json`: https://github.com/maddyonline/weathergpt/commit/fe9ab6a3bf62d6dfa1d9d86b7c113730f088e83b.

Are there additional steps for ChatGPT plugin marketplace to recognize this plugin? FWIW, installing "weathergpt.vercel.app" works fine.

![Screenshot 2023-04-14 at 3 17 09 PM](https://user-images.githubusercontent.com/6402895/232163899-5afa324c-6934-4a4b-9a5a-c32954a2cc6b.png)

**Comment by steven-tey** [comment]
Hey! If you're developing your own version of this you'll need to click on "Develop your own plugin" instead – will clarify this in the README! 🙏 

![CleanShot 2023-04-14 at 17 21 56](https://user-images.githubusercontent.com/28986134/232164493-9f324422-e684-4d15-9bd9-cd315361912b.png)

**Comment by steven-tey** [comment]
Added some further instructions here: https://github.com/steven-tey/weathergpt/blob/main/README.md#deploy-your-own

**Comment by maddyonline** [comment]
Thanks with the updated instructions, I was able to get it to work. Thanks again!
